version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing root dependencies...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Running build...
      - npm run build
      - echo Installing backend production dependencies...
      - cd src/backend
      - npm install --production
      - cd ../..
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating deployment package...
      - cd src/backend
      - zip -r ../../deploy.zip . -x "*.git*" "node_modules/.cache/*"
      - cd ../..
      - echo Deployment package created at deploy.zip

artifacts:
  files:
    - 'deploy.zip'
    - 'src/backend/node_modules/**/*'

cache:
  paths:
    - 'node_modules/**/*'
    - 'src/backend/node_modules/**/*' 
