version: "3"

services:
  frontend:
    image: 320005330206.dkr.ecr.eu-north-1.amazonaws.com/reblog-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - blog-network

  backend:
    image: 320005330206.dkr.ecr.eu-north-1.amazonaws.com/reblog-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/app/src/backend
      - /app/node_modules
    environment:
      - REDIS_URL=redis:6379
      - NODE_ENV=development
    depends_on:
      - redis
    networks:
      - blog-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - blog-network
    command: ["redis-server", "--appendonly", "yes"]

networks:
  blog-network:
    driver: bridge

volumes:
  redis-data:
    driver: local