name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: reblog-app
  EB_APPLICATION_NAME: reblog-app
  EB_ENVIRONMENT_NAME: reblog-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push frontend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG -f Dockerfile .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG

    - name: Build and push backend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:backend-$IMAGE_TAG -f Dockerfile.backend .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend-$IMAGE_TAG

    - name: Generate Dockerrun.aws.json
      run: |
        cat > Dockerrun.aws.json << EOF
        {
          "AWSEBDockerrunVersion": "3",
          "containerDefinitions": [
            {
              "name": "frontend",
              "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:frontend-${{ github.sha }}",
              "essential": true,
              "memory": 512,
              "portMappings": [
                {
                  "hostPort": 80,
                  "containerPort": 80
                }
              ]
            },
            {
              "name": "backend",
              "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:backend-${{ github.sha }}",
              "essential": true,
              "memory": 512,
              "portMappings": [
                {
                  "hostPort": 5000,
                  "containerPort": 5000
                }
              ],
              "environment": [
                {
                  "name": "REDIS_URL",
                  "value": "redis://redis:6379"
                },
                {
                  "name": "NODE_ENV",
                  "value": "production"
                }
              ]
            },
            {
              "name": "redis",
              "image": "redis:alpine",
              "essential": true,
              "memory": 256,
              "command": ["redis-server", "--appendonly", "yes"]
            }
          ]
        }
        EOF

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ env.AWS_REGION }}
        deployment_package: Dockerrun.aws.json 